// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtiJAzsA-aWBekk1z4JEv1jWk0PkMGwMo',
    appId: '1:462498962687:web:8f5ba7e03f5a896386c0ca',
    messagingSenderId: '462498962687',
    projectId: 'valguide2-3bf07',
    authDomain: 'valguide2-3bf07.firebaseapp.com',
    storageBucket: 'valguide2-3bf07.appspot.com',
    measurementId: 'G-EVCJD8YDNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHkZ3NzJQRqYakzeqEzyy0cXRLqwtySw',
    appId: '1:462498962687:android:62597501ef52ba5786c0ca',
    messagingSenderId: '462498962687',
    projectId: 'valguide2-3bf07',
    storageBucket: 'valguide2-3bf07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdVanOvUPJ-bXr5B22J8v9EH_VvXb-2Lc',
    appId: '1:462498962687:ios:0f333c335ec2aebe86c0ca',
    messagingSenderId: '462498962687',
    projectId: 'valguide2-3bf07',
    storageBucket: 'valguide2-3bf07.appspot.com',
    androidClientId: '462498962687-kg9nfero7p70uui7o4sbrg1578u6d8ve.apps.googleusercontent.com',
    iosClientId: '462498962687-ssrsgjg3p91e2j62i0r949revbvva9ln.apps.googleusercontent.com',
    iosBundleId: 'com.amjad.valguide3.valguide3',
  );
}
